[package]
name = "mfind"
version = "0.1.0"
authors = ["Daniel Wehner <daniel@tag1consulting.com>"]

[dependencies]
  docopt = "0.6.78"
  rustc-serialize = "0.3.18"
  regex = "0.1.55"
  walkdir = "0.1.5"

